/* ParserAST.java */
/* Generated By:JavaCC: Do not edit this line. ParserAST.java */
    package edu.purdue.cs352.minijava.parser;

    import edu.purdue.cs352.minijava.ast.*;
    import edu.purdue.cs352.minijava.*;
    import java.util.*;

    public class ParserAST implements ParserASTConstants {
        public static void main(String[] args) {
            ParserAST parser;

            if (args.length != 1) {
                System.out.println("Use: mjparse <input file>");
                return;
            }

            try {
                parser = new ParserAST(new java.io.FileInputStream(args[0]));
            } catch (java.io.FileNotFoundException ex) {
                System.out.println("File " + args[0] + " not found.");
                return;
            }

            try {
                parser.Program();
            } catch (ParseException ex) {
                System.out.println(ex.getMessage());
                return;
            }
        }

/* The following is a simple grammar that will allow you to test the generated
 * lexer. */
  final public List<Token> TokenList() throws ParseException {Token t;
    List<Token> tl = new ArrayList<Token>();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case KW_CLASS:
      case KW_PUBLIC:
      case KW_STATIC:
      case KW_VOID:
      case KW_MAIN:
      case KW_STRING:
      case KW_EXTENDS:
      case KW_RETURN:
      case KW_INT:
      case KW_BOOLEAN:
      case KW_IF:
      case KW_ELSE:
      case KW_WHILE:
      case KW_TRUE:
      case KW_FALSE:
      case KW_THIS:
      case KW_NEW:
      case KW_PRINT:
      case SYM_LBRACE:
      case SYM_RBRACE:
      case SYM_LPARENTHESE:
      case SYM_RPARENTHESE:
      case SYM_LBRACKET:
      case SYM_RBRACKET:
      case SYM_SEMICOLON:
      case SYM_EQUAL:
      case SYM_AND:
      case SYM_OR:
      case SYM_LESS:
      case SYM_LESSEQUAL:
      case SYM_EQUALEQUAL:
      case SYM_NOTEQUAL:
      case SYM_GREATER:
      case SYM_GREATEREQUAL:
      case SYM_PLUS:
      case SYM_MINUS:
      case SYM_MULTIPLICATION:
      case SYM_DIVIDE:
      case SYM_MOD:
      case SYM_NOT:
      case SYM_DOT:
      case SYM_COMMA:
      case IDENTIFIER:
      case INT_LITERAL:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      t = Token();
tl.add(t);
    }
    jj_consume_token(0);
{if ("" != null) return tl;}
    throw new Error("Missing return statement in function");
  }

  final public Token Token() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case KW_CLASS:{
      jj_consume_token(KW_CLASS);
      break;
      }
    case KW_PUBLIC:{
      jj_consume_token(KW_PUBLIC);
      break;
      }
    case KW_STATIC:{
      jj_consume_token(KW_STATIC);
      break;
      }
    case KW_VOID:{
      jj_consume_token(KW_VOID);
      break;
      }
    case KW_MAIN:{
      jj_consume_token(KW_MAIN);
      break;
      }
    case KW_STRING:{
      jj_consume_token(KW_STRING);
      break;
      }
    case KW_EXTENDS:{
      jj_consume_token(KW_EXTENDS);
      break;
      }
    case KW_RETURN:{
      jj_consume_token(KW_RETURN);
      break;
      }
    case KW_INT:{
      jj_consume_token(KW_INT);
      break;
      }
    case KW_BOOLEAN:{
      jj_consume_token(KW_BOOLEAN);
      break;
      }
    case KW_IF:{
      jj_consume_token(KW_IF);
      break;
      }
    case KW_ELSE:{
      jj_consume_token(KW_ELSE);
      break;
      }
    case KW_WHILE:{
      jj_consume_token(KW_WHILE);
      break;
      }
    case KW_TRUE:{
      jj_consume_token(KW_TRUE);
      break;
      }
    case KW_FALSE:{
      jj_consume_token(KW_FALSE);
      break;
      }
    case KW_THIS:{
      jj_consume_token(KW_THIS);
      break;
      }
    case KW_NEW:{
      jj_consume_token(KW_NEW);
      break;
      }
    case KW_PRINT:{
      jj_consume_token(KW_PRINT);
      break;
      }
    case SYM_LBRACE:{
      jj_consume_token(SYM_LBRACE);
      break;
      }
    case SYM_RBRACE:{
      jj_consume_token(SYM_RBRACE);
      break;
      }
    case SYM_LPARENTHESE:{
      jj_consume_token(SYM_LPARENTHESE);
      break;
      }
    case SYM_RPARENTHESE:{
      jj_consume_token(SYM_RPARENTHESE);
      break;
      }
    case SYM_LBRACKET:{
      jj_consume_token(SYM_LBRACKET);
      break;
      }
    case SYM_RBRACKET:{
      jj_consume_token(SYM_RBRACKET);
      break;
      }
    case SYM_SEMICOLON:{
      jj_consume_token(SYM_SEMICOLON);
      break;
      }
    case SYM_EQUAL:{
      jj_consume_token(SYM_EQUAL);
      break;
      }
    case SYM_AND:{
      jj_consume_token(SYM_AND);
      break;
      }
    case SYM_OR:{
      jj_consume_token(SYM_OR);
      break;
      }
    case SYM_LESS:{
      jj_consume_token(SYM_LESS);
      break;
      }
    case SYM_LESSEQUAL:{
      jj_consume_token(SYM_LESSEQUAL);
      break;
      }
    case SYM_EQUALEQUAL:{
      jj_consume_token(SYM_EQUALEQUAL);
      break;
      }
    case SYM_NOTEQUAL:{
      jj_consume_token(SYM_NOTEQUAL);
      break;
      }
    case SYM_GREATER:{
      jj_consume_token(SYM_GREATER);
      break;
      }
    case SYM_GREATEREQUAL:{
      jj_consume_token(SYM_GREATEREQUAL);
      break;
      }
    case SYM_PLUS:{
      jj_consume_token(SYM_PLUS);
      break;
      }
    case SYM_MINUS:{
      jj_consume_token(SYM_MINUS);
      break;
      }
    case SYM_MULTIPLICATION:{
      jj_consume_token(SYM_MULTIPLICATION);
      break;
      }
    case SYM_DIVIDE:{
      jj_consume_token(SYM_DIVIDE);
      break;
      }
    case SYM_MOD:{
      jj_consume_token(SYM_MOD);
      break;
      }
    case SYM_NOT:{
      jj_consume_token(SYM_NOT);
      break;
      }
    case SYM_DOT:{
      jj_consume_token(SYM_DOT);
      break;
      }
    case SYM_COMMA:{
      jj_consume_token(SYM_COMMA);
      break;
      }
    case IDENTIFIER:{
      jj_consume_token(IDENTIFIER);
      break;
      }
    case INT_LITERAL:{
      jj_consume_token(INT_LITERAL);
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return token;}
    throw new Error("Missing return statement in function");
  }

// Grammar
  final public Program Program() throws ParseException {Main main;
    List<ClassDecl> cds = new ArrayList<ClassDecl>();
    ClassDecl temp;
    main = MainClass();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case KW_CLASS:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      temp = ClassDeclaration();
cds.add(temp);
    }
    jj_consume_token(0);
{if ("" != null) return new Program(new Token(), main, cds);}
    throw new Error("Missing return statement in function");
  }

  final public Main MainClass() throws ParseException {Statement statement;
    Token tok;
    tok = jj_consume_token(KW_CLASS);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(SYM_LBRACE);
    jj_consume_token(KW_PUBLIC);
    jj_consume_token(KW_STATIC);
    jj_consume_token(KW_VOID);
    jj_consume_token(KW_MAIN);
    jj_consume_token(SYM_LPARENTHESE);
    jj_consume_token(KW_STRING);
    jj_consume_token(SYM_LBRACKET);
    jj_consume_token(SYM_RBRACKET);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(SYM_RPARENTHESE);
    jj_consume_token(SYM_LBRACE);
    statement = Statement();
    jj_consume_token(SYM_RBRACE);
    jj_consume_token(SYM_RBRACE);
{if ("" != null) return new Main(tok, statement);}
    throw new Error("Missing return statement in function");
  }

  final public ClassDecl ClassDeclaration() throws ParseException {Token clas, tok;
    String name = null, eggstends = null;
    VarDecl t1;
    MethodDecl t2;
    List<VarDecl> fields = new ArrayList<VarDecl>();
    List<MethodDecl> methods = new ArrayList<MethodDecl>();
    clas = jj_consume_token(KW_CLASS);
    tok = jj_consume_token(IDENTIFIER);
name = tok.toString();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case KW_EXTENDS:{
      jj_consume_token(KW_EXTENDS);
      tok = jj_consume_token(IDENTIFIER);
eggstends = tok.toString();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    jj_consume_token(SYM_LBRACE);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case KW_INT:
      case KW_BOOLEAN:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      t1 = VarDeclaration();
fields.add(t1);
    }
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case KW_PUBLIC:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_4;
      }
      t2 = MethodDeclaration();
methods.add(t2);
    }
    jj_consume_token(SYM_RBRACE);
{if ("" != null) return new ClassDecl(clas, name, eggstends, fields, methods);}
    throw new Error("Missing return statement in function");
  }

  final public VarDecl VarDeclaration() throws ParseException {Token tok;
    Type type;
    String name;
    type = Type();
    tok = jj_consume_token(IDENTIFIER);
    jj_consume_token(SYM_SEMICOLON);
{if ("" != null) return new VarDecl(tok, type, tok.toString());}
    throw new Error("Missing return statement in function");
  }

  final public MethodDecl MethodDeclaration() throws ParseException {Token tok, temp_tok;
    Type retType, temp_type;
    String name;
    Parameter t1;
    VarDecl   t2;
    Statement t3;
    List<Parameter> parameters = new ArrayList<Parameter>();
    List<VarDecl> vds = new ArrayList<VarDecl>();
    List<Statement> body = new ArrayList<Statement>();
    Exp retExp;
    jj_consume_token(KW_PUBLIC);
    retType = Type();
    tok = jj_consume_token(IDENTIFIER);
name = tok.toString();
    jj_consume_token(SYM_LPARENTHESE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case KW_INT:
    case KW_BOOLEAN:
    case IDENTIFIER:{
      temp_type = Type();
      temp_tok = jj_consume_token(IDENTIFIER);
parameters.add(new Parameter(new Token(),temp_type, temp_tok.toString()));
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SYM_COMMA:{
          ;
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          break label_5;
        }
        jj_consume_token(SYM_COMMA);
        temp_type = Type();
        temp_tok = jj_consume_token(IDENTIFIER);
parameters.add(new Parameter(new Token(),temp_type, temp_tok.toString()));
      }
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    jj_consume_token(SYM_RPARENTHESE);
    jj_consume_token(SYM_LBRACE);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case KW_INT:
      case KW_BOOLEAN:
      case KW_IF:
      case KW_WHILE:
      case KW_TRUE:
      case KW_FALSE:
      case KW_THIS:
      case KW_NEW:
      case KW_PRINT:
      case SYM_LBRACE:
      case SYM_LPARENTHESE:
      case SYM_NOT:
      case IDENTIFIER:
      case INT_LITERAL:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_6;
      }
      if (jj_2_1(2)) {
        t2 = VarDeclaration();
vds.add(t2);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case KW_IF:
        case KW_WHILE:
        case KW_TRUE:
        case KW_FALSE:
        case KW_THIS:
        case KW_NEW:
        case KW_PRINT:
        case SYM_LBRACE:
        case SYM_LPARENTHESE:
        case SYM_NOT:
        case IDENTIFIER:
        case INT_LITERAL:{
          t3 = Statement();
body.add(t3);
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    jj_consume_token(KW_RETURN);
    retExp = Expression();
    jj_consume_token(SYM_SEMICOLON);
    jj_consume_token(SYM_RBRACE);
{if ("" != null) return new MethodDecl(tok, retType, name, parameters, vds, body, retExp);}
    throw new Error("Missing return statement in function");
  }

  final public Type Type() throws ParseException {Token tok;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case KW_INT:{
      tok = jj_consume_token(KW_INT);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SYM_LBRACKET:{
        jj_consume_token(SYM_LBRACKET);
        jj_consume_token(SYM_RBRACKET);
{if ("" != null) return new TypeIntArray(tok);}
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        ;
      }
{if ("" != null) return new TypeInt(tok);}
      break;
      }
    case KW_BOOLEAN:{
      tok = jj_consume_token(KW_BOOLEAN);
{if ("" != null) return new TypeBoolean(tok);}
      break;
      }
    case IDENTIFIER:{
      tok = jj_consume_token(IDENTIFIER);
{if ("" != null) return new Type(tok, tok.toString());}
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Statement Statement() throws ParseException {Token tok;
    List<Statement> body = new ArrayList<Statement>();
    Statement s = null, ifS = null, elseS = null , t;
    Exp exp;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SYM_LBRACE:{
      tok = jj_consume_token(SYM_LBRACE);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case KW_IF:
        case KW_WHILE:
        case KW_TRUE:
        case KW_FALSE:
        case KW_THIS:
        case KW_NEW:
        case KW_PRINT:
        case SYM_LBRACE:
        case SYM_LPARENTHESE:
        case SYM_NOT:
        case IDENTIFIER:
        case INT_LITERAL:{
          ;
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          break label_7;
        }
        t = Statement();
body.add(t);
      }
      jj_consume_token(SYM_RBRACE);
s = new BlockStatement(tok, body);
      break;
      }
    case KW_IF:{
      tok = jj_consume_token(KW_IF);
      jj_consume_token(SYM_LPARENTHESE);
      exp = Expression();
      jj_consume_token(SYM_RPARENTHESE);
      ifS = Statement();
      if (jj_2_2(2)) {
        jj_consume_token(KW_ELSE);
        elseS = Statement();
      } else {
        ;
      }
s = new IfStatement(tok, exp, ifS, elseS);
      break;
      }
    case KW_WHILE:{
      tok = jj_consume_token(KW_WHILE);
      jj_consume_token(SYM_LPARENTHESE);
      exp = Expression();
      jj_consume_token(SYM_RPARENTHESE);
      s = Statement();
s = new WhileStatement(tok, exp, s);
      break;
      }
    case KW_PRINT:{
      tok = jj_consume_token(KW_PRINT);
      jj_consume_token(SYM_LPARENTHESE);
      exp = Expression();
      jj_consume_token(SYM_RPARENTHESE);
      jj_consume_token(SYM_SEMICOLON);
s = new PrintStatement(tok, exp);
      break;
      }
    case KW_TRUE:
    case KW_FALSE:
    case KW_THIS:
    case KW_NEW:
    case SYM_LPARENTHESE:
    case SYM_NOT:
    case IDENTIFIER:
    case INT_LITERAL:{
      exp = Expression();
      jj_consume_token(SYM_SEMICOLON);
s = new ExpStatement(new Token(), exp);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return s;}
    throw new Error("Missing return statement in function");
  }

  final public Exp Expression() throws ParseException {Exp exp = null;
    exp = AssignExpr();
{if ("" != null) return exp;}
    throw new Error("Missing return statement in function");
  }

  final public Exp AssignExpr() throws ParseException {Exp target, value;
    target = LogicOp();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SYM_EQUAL:{
      jj_consume_token(SYM_EQUAL);
      value = AssignExpr();
{if ("" != null) return new AssignExp(new Token(), target ,value);}
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      ;
    }
{if ("" != null) return target;}
    throw new Error("Missing return statement in function");
  }

  final public Exp LogicOp() throws ParseException {Exp left;
    Exp right;
    Token tok;
    left = CmpOp();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SYM_AND:
      case SYM_OR:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SYM_AND:{
        tok = jj_consume_token(SYM_AND);
        break;
        }
      case SYM_OR:{
        tok = jj_consume_token(SYM_OR);
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = CmpOp();
left = new BinaryExp(left, tok, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
  }

  final public Exp CmpOp() throws ParseException {Exp left;
    Exp right;
    Token tok;
    left = AddOp();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SYM_LESS:
      case SYM_LESSEQUAL:
      case SYM_NOTEQUAL:
      case SYM_GREATER:
      case SYM_GREATEREQUAL:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SYM_LESS:{
        tok = jj_consume_token(SYM_LESS);
        break;
        }
      case SYM_LESSEQUAL:{
        tok = jj_consume_token(SYM_LESSEQUAL);
        break;
        }
      case SYM_NOTEQUAL:{
        tok = jj_consume_token(SYM_NOTEQUAL);
        break;
        }
      case SYM_GREATER:{
        tok = jj_consume_token(SYM_GREATER);
        break;
        }
      case SYM_GREATEREQUAL:{
        tok = jj_consume_token(SYM_GREATEREQUAL);
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = AddOp();
left = new BinaryExp(left, tok, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
  }

  final public Exp AddOp() throws ParseException {Exp left;
    Exp right;
    Token tok;
    left = MulOp();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SYM_PLUS:
      case SYM_MINUS:{
        ;
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SYM_PLUS:{
        tok = jj_consume_token(SYM_PLUS);
        break;
        }
      case SYM_MINUS:{
        tok = jj_consume_token(SYM_MINUS);
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = MulOp();
left = new BinaryExp(left, tok, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
  }

  final public Exp MulOp() throws ParseException {Exp left;
    Exp right;
    Token tok;
    left = UnaryOp();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SYM_MULTIPLICATION:
      case SYM_DIVIDE:
      case SYM_MOD:{
        ;
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SYM_MULTIPLICATION:{
        tok = jj_consume_token(SYM_MULTIPLICATION);
        break;
        }
      case SYM_DIVIDE:{
        tok = jj_consume_token(SYM_DIVIDE);
        break;
        }
      case SYM_MOD:{
        tok = jj_consume_token(SYM_MOD);
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = UnaryOp();
left = new BinaryExp(left, tok, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
  }

  final public Exp UnaryOp() throws ParseException {Exp sub;
    Token tok;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SYM_NOT:{
      tok = jj_consume_token(SYM_NOT);
      sub = UnaryOp();
{if ("" != null) return new NotExp(tok, sub);}
      break;
      }
    case KW_TRUE:
    case KW_FALSE:
    case KW_THIS:
    case KW_NEW:
    case SYM_LPARENTHESE:
    case IDENTIFIER:
    case INT_LITERAL:{
      sub = PostfixOp();
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return sub;}
    throw new Error("Missing return statement in function");
  }

  final public Exp PostfixOp() throws ParseException {Exp target, sub, t;
    Token tok = null;
    String method;
    List<Exp> arguments = new ArrayList<Exp>();
    target = PrimaryExp();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SYM_LBRACKET:
      case SYM_DOT:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SYM_LBRACKET:{
        jj_consume_token(SYM_LBRACKET);
        sub = Expression();
        jj_consume_token(SYM_RBRACKET);
target = new IndexExp(tok, target, sub);
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        if (jj_2_3(3)) {
          jj_consume_token(SYM_DOT);
          tok = Identifier();
method = tok.toString();
          jj_consume_token(SYM_LPARENTHESE);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case KW_TRUE:
          case KW_FALSE:
          case KW_THIS:
          case KW_NEW:
          case SYM_LPARENTHESE:
          case SYM_NOT:
          case IDENTIFIER:
          case INT_LITERAL:{
            t = Expression();
arguments.add(t);
            label_13:
            while (true) {
              switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
              case SYM_COMMA:{
                ;
                break;
                }
              default:
                jj_la1[25] = jj_gen;
                break label_13;
              }
              jj_consume_token(SYM_COMMA);
              t = Expression();
arguments.add(t);
            }
            break;
            }
          default:
            jj_la1[26] = jj_gen;
            ;
          }
          jj_consume_token(SYM_RPARENTHESE);
target = new CallExp(tok, target, method, arguments);
        } else {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case SYM_DOT:{
            jj_consume_token(SYM_DOT);
            tok = Identifier();
target = new MemberExp(tok, target ,tok.toString());
            break;
            }
          default:
            jj_la1[28] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    }
{if ("" != null) return target;}
    throw new Error("Missing return statement in function");
  }

  final public Exp PrimaryExp() throws ParseException {Exp size, exp;
    Token tok;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT_LITERAL:{
      tok = jj_consume_token(INT_LITERAL);
{if ("" != null) return new IntLiteralExp(tok, Integer.parseInt(tok.toString()));}
      break;
      }
    case KW_TRUE:{
      tok = jj_consume_token(KW_TRUE);
{if ("" != null) return new BooleanLiteralExp(tok, true);}
      break;
      }
    case KW_FALSE:{
      tok = jj_consume_token(KW_FALSE);
{if ("" != null) return new BooleanLiteralExp(tok, false);}
      break;
      }
    case IDENTIFIER:{
      tok = Identifier();
{if ("" != null) return new VarExp(tok, tok.toString());}
      break;
      }
    case KW_THIS:{
      tok = jj_consume_token(KW_THIS);
{if ("" != null) return new ThisExp(tok);}
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      if (jj_2_4(2)) {
        jj_consume_token(KW_NEW);
        jj_consume_token(KW_INT);
        jj_consume_token(SYM_LBRACKET);
        size = Expression();
        jj_consume_token(SYM_RBRACKET);
{if ("" != null) return new NewIntArrayExp(new Token(), size);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case KW_NEW:{
          jj_consume_token(KW_NEW);
          tok = Identifier();
          jj_consume_token(SYM_LPARENTHESE);
          jj_consume_token(SYM_RPARENTHESE);
{if ("" != null) return new NewObjectExp(tok, tok.toString());}
          break;
          }
        case SYM_LPARENTHESE:{
          jj_consume_token(SYM_LPARENTHESE);
          exp = Expression();
          jj_consume_token(SYM_RPARENTHESE);
{if ("" != null) return exp;}
          break;
          }
        default:
          jj_la1[30] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public Token Identifier() throws ParseException {Token t1 = null;
    t1 = jj_consume_token(IDENTIFIER);
{if ("" != null) return t1;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_3R_36()
 {
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3R_31()
 {
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_16()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_34()
 {
    if (jj_scan_token(SYM_NOT)) return true;
    return false;
  }

  private boolean jj_3R_26()
 {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3R_44()
 {
    if (jj_scan_token(SYM_LPARENTHESE)) return true;
    return false;
  }

  private boolean jj_3R_43()
 {
    if (jj_scan_token(KW_NEW)) return true;
    return false;
  }

  private boolean jj_3R_33()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) return true;
    }
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_scan_token(KW_NEW)) return true;
    if (jj_scan_token(KW_INT)) return true;
    return false;
  }

  private boolean jj_3R_42()
 {
    if (jj_scan_token(KW_THIS)) return true;
    return false;
  }

  private boolean jj_3R_30()
 {
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3R_41()
 {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_22()
 {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_40()
 {
    if (jj_scan_token(KW_FALSE)) return true;
    return false;
  }

  private boolean jj_3R_21()
 {
    if (jj_scan_token(KW_PRINT)) return true;
    return false;
  }

  private boolean jj_3R_39()
 {
    if (jj_scan_token(KW_TRUE)) return true;
    return false;
  }

  private boolean jj_3R_20()
 {
    if (jj_scan_token(KW_WHILE)) return true;
    return false;
  }

  private boolean jj_3R_19()
 {
    if (jj_scan_token(KW_IF)) return true;
    return false;
  }

  private boolean jj_3R_27()
 {
    if (jj_scan_token(SYM_LBRACKET)) return true;
    return false;
  }

  private boolean jj_3R_38()
 {
    if (jj_scan_token(INT_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_37()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_18()
 {
    if (jj_scan_token(SYM_LBRACE)) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_scan_token(SYM_DOT)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(SYM_LPARENTHESE)) return true;
    return false;
  }

  private boolean jj_3R_15()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_14()
 {
    if (jj_3R_17()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_32()
 {
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_scan_token(KW_ELSE)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_29()
 {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3R_35()
 {
    if (jj_3R_36()) return true;
    return false;
  }

  private boolean jj_3R_25()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_24()
 {
    if (jj_scan_token(KW_BOOLEAN)) return true;
    return false;
  }

  private boolean jj_3R_17()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_23()
 {
    if (jj_scan_token(KW_INT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_27()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_28()
 {
    if (jj_3R_29()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public ParserASTTokenManager token_source;
  JavaCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[31];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xffffff00,0xffffff00,0x100,0x4000,0x30000,0x200,0x0,0x30000,0x17f70000,0x17f40000,0x40000000,0x30000,0x17f40000,0x17f40000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x11e00000,0x40000000,0x0,0x11e00000,0x40000000,0x0,0xe00000,0x11000000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0xfffff,0xfffff,0x0,0x0,0x40000,0x0,0x20000,0x40000,0xc8000,0xc8000,0x0,0x40000,0xc8000,0xc8000,0x2,0xc,0xc,0x3b0,0x3b0,0xc00,0xc00,0x7000,0x7000,0xc8000,0x10000,0x20000,0xc8000,0x0,0x10000,0xc0000,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[4];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public ParserAST(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ParserAST(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserASTTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 31; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 31; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public ParserAST(java.io.Reader stream) {
    jj_input_stream = new JavaCharStream(stream, 1, 1);
    token_source = new ParserASTTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 31; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 31; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public ParserAST(ParserASTTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 31; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserASTTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 31; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[52];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 31; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 52; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 4; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

    }
